### PR TITLE
Add logback json packages to support JSON format logback config

### PR DESCRIPTION
**Pull request by arnisoph**
```
$ java -Dspring.main.banner-mode=off -Dlogging.config=$PWD/logback.xml -jar axonserver/target/axonserver-4.3-SNAPSHOT-exec.jar
23:07:48.030 [main] INFO org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.
{"timestamp":"2019-10-11T21:07:49.661Z","level":"INFO","thread":"main","logger":"io.axoniq.axonserver.AxonServer","message":"Starting AxonServer on lap-abechtoldt01.fritz.box with PID 39695 (/Users/ab/Documents/dev/github/axon-server-se/axonserver/target/axonserver-4.3-SNAPSHOT-exec.jar started by ab in /Users/ab/Documents/dev/github/axon-server-se)","context":"default"}
{"timestamp":"2019-10-11T21:07:49.697Z","level":"INFO","thread":"main","logger":"io.axoniq.axonserver.AxonServer","message":"No active profile set, falling back to default profiles: default","context":"default"}
{"timestamp":"2019-10-11T21:07:55.649Z","level":"INFO","thread":"main","logger":"org.springframework.boot.web.embedded.tomcat.TomcatWebServer","message":"Tomcat initialized with port(s): 8024 (http)","context":"default"}
^C
```

Screenshot 2019-10-11 at 23 12 10

### CODE REVIEW

**Comment by janesser** [comment]
@MGathier is there chance this would make it into the 4.2.X release?

**Comment by MGathier** [comment]
@janesser we will include this in the next 4.2.x release as we agree that this is useful. By the way, in Axon Server enterprise you could just add the jar files in the exts folder and they would be picked up automatically.

**Comment by arnisoph** [comment]
> Please change the sample logback configuration to have the same logging levels as the normal logging.

please check again

**Comment by MGathier** [comment]
I will merge the change into the master, and then cherrypick it into 4.2.x branch.

**Comment by arnisoph** [comment]
You're welcome!

**Pull request merged**
